#Enter the URL of your unban website
URL: 'http://yoururlhere.com/unban/'
#The reply key you have set in your config.php
URLKey: 'CHANGEME'
#Time in seconds how often we check for any pending unbans
UnbanInterval: 120
#The command (or commands) you want to be ran on the player you are unbanning, use %player% as the placeholder, and '-' to separate commands
Command: 'unban %player%-eco set %player% 0'
#Probably want this disabled
StackTrace: false
